////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.loc.gov/standards/alto/ns-v4#", ClrNamespace="www.loc.gov.standards.alto.nsv4")]

//namespace Ocr.Wrapper.ToAlto.Xsd.AltoFormat
//{
//    using System;
//    using System.Runtime.Serialization;
    
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(ElementName="alto", Namespace="http://www.loc.gov/standards/alto/ns-v4#", IsNullable=false)]
//    public partial class altoType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("altoType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class DescriptionType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("DescriptionType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementUnitType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum MeasurementUnitType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        pixel = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        mm10 = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        inch1200 = 2,
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class sourceImageInformationType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("sourceImageInformationType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class StylesType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("StylesType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class TagsType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("TagsType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="QualityType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum QualityType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        OK = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Missing = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute(Value="Missing in original")]
//        Missinginoriginal = 2,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Damaged = 3,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Retained = 4,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Target = 5,
        
//        [System.Runtime.Serialization.EnumMemberAttribute(Value="As in original")]
//        Asinoriginal = 6,
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="PositionType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum PositionType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Left = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Right = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Foldout = 2,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Single = 3,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Cover = 4,
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class PageType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("PageType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class LayoutType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("LayoutType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class TextStyleType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("TextStyleType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class ParagraphStyleType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ParagraphStyleType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class BlockType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("BlockType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class SPType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SPType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="SUBS_TYPEType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum SUBS_TYPEType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        HypPart1 = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        HypPart2 = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Abbreviation = 2,
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class ALTERNATIVEType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ALTERNATIVEType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class StringType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("StringType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class PageSpaceType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("PageSpaceType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class ShapeType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ShapeType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class PolygonType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("PolygonType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class EllipseType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("EllipseType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class CircleType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("CircleType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="fontTypeType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum fontTypeType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        serif = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute(Value="sans-serif")]
//        sansserif = 1,
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="fontWidthType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum fontWidthType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        proportional = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        @fixed = 1,
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class fileIdentifierType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("fileIdentifierType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class documentIdentifierType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("documentIdentifierType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class ocrProcessingType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ocrProcessingType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class processingStepType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("processingStepType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.FlagsAttribute()]
//    [System.Runtime.Serialization.DataContractAttribute(Name="processingCategoryType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    public enum processingCategoryType : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        contentGeneration = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        contentModification = 2,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        preOperation = 4,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        postOperation = 8,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        other = 16,
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class dateTimeType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("dateTimeType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="processingSoftwareType", Namespace="http://www.loc.gov/standards/alto/ns-v4#")]
//    [System.SerializableAttribute()]
//    public partial class processingSoftwareType : object, System.Runtime.Serialization.IExtensibleDataObject
//    {
        
//        [System.NonSerializedAttribute()]
//        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private string softwareCreatorField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private string softwareNameField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private string softwareVersionField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private string applicationDescriptionField;
        
//        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
//        {
//            get
//            {
//                return this.extensionDataField;
//            }
//            set
//            {
//                this.extensionDataField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
//        public string softwareCreator
//        {
//            get
//            {
//                return this.softwareCreatorField;
//            }
//            set
//            {
//                this.softwareCreatorField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
//        public string softwareName
//        {
//            get
//            {
//                return this.softwareNameField;
//            }
//            set
//            {
//                this.softwareNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
//        public string softwareVersion
//        {
//            get
//            {
//                return this.softwareVersionField;
//            }
//            set
//            {
//                this.softwareVersionField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
//        public string applicationDescription
//        {
//            get
//            {
//                return this.applicationDescriptionField;
//            }
//            set
//            {
//                this.applicationDescriptionField = value;
//            }
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class ComposedBlockType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ComposedBlockType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class IllustrationType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("IllustrationType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class GraphicalElementType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("GraphicalElementType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class TextBlockType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("TextBlockType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class TagType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("TagType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class GlyphType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("GlyphType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
//    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
//    public partial class VariantType : object, System.Xml.Serialization.IXmlSerializable
//    {
        
//        private System.Xml.XmlNode[] nodesField;
        
//        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("VariantType", "http://www.loc.gov/standards/alto/ns-v4#");
        
//        public System.Xml.XmlNode[] Nodes
//        {
//            get
//            {
//                return this.nodesField;
//            }
//            set
//            {
//                this.nodesField = value;
//            }
//        }
        
//        public void ReadXml(System.Xml.XmlReader reader)
//        {
//            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
//        }
        
//        public void WriteXml(System.Xml.XmlWriter writer)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
//        }
        
//        public System.Xml.Schema.XmlSchema GetSchema()
//        {
//            return null;
//        }
        
//        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
//        {
//            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
//            return typeName;
//        }
//    }

//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.FlagsAttribute()]
//    [System.Runtime.Serialization.DataContractAttribute(Name = "", Namespace = "")]
//    public enum GeneratedType : int
//    {

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        bold = 1,

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        italics = 2,

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        subscript = 4,

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        superscript = 8,

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        smallcaps = 16,

//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        underline = 32,
//    }
//}
